#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-data.tree
Version  : 1.0.0
Release  : 1
URL      : https://cran.r-project.org/src/contrib/data.tree_1.0.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/data.tree_1.0.0.tar.gz
Summary  : General Purpose Hierarchical Data Structure
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-R6
Requires: R-stringi
BuildRequires : R-R6
BuildRequires : R-ape
BuildRequires : R-igraph
BuildRequires : R-party
BuildRequires : R-partykit
BuildRequires : R-stringi
BuildRequires : buildreq-R

%description
tree in various orders. Aggregate, cumulate, print, plot, convert to and from
    data.frame and more. Useful for decision trees, machine learning, finance,
    conversion from and to JSON, and many other applications.

%prep
%setup -q -c -n data.tree
cd %{_builddir}/data.tree

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641319023

%install
export SOURCE_DATE_EPOCH=1641319023
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library data.tree
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library data.tree
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library data.tree
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc data.tree || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/data.tree/DESCRIPTION
/usr/lib64/R/library/data.tree/INDEX
/usr/lib64/R/library/data.tree/Meta/Rd.rds
/usr/lib64/R/library/data.tree/Meta/data.rds
/usr/lib64/R/library/data.tree/Meta/features.rds
/usr/lib64/R/library/data.tree/Meta/hsearch.rds
/usr/lib64/R/library/data.tree/Meta/links.rds
/usr/lib64/R/library/data.tree/Meta/nsInfo.rds
/usr/lib64/R/library/data.tree/Meta/package.rds
/usr/lib64/R/library/data.tree/Meta/vignette.rds
/usr/lib64/R/library/data.tree/NAMESPACE
/usr/lib64/R/library/data.tree/NEWS
/usr/lib64/R/library/data.tree/R/data.tree
/usr/lib64/R/library/data.tree/R/data.tree.rdb
/usr/lib64/R/library/data.tree/R/data.tree.rdx
/usr/lib64/R/library/data.tree/data/acme.rda
/usr/lib64/R/library/data.tree/data/mushroom.rda
/usr/lib64/R/library/data.tree/doc/applications.R
/usr/lib64/R/library/data.tree/doc/applications.Rmd
/usr/lib64/R/library/data.tree/doc/applications.html
/usr/lib64/R/library/data.tree/doc/data.tree.R
/usr/lib64/R/library/data.tree/doc/data.tree.Rmd
/usr/lib64/R/library/data.tree/doc/data.tree.html
/usr/lib64/R/library/data.tree/doc/index.html
/usr/lib64/R/library/data.tree/extdata/flare.json
/usr/lib64/R/library/data.tree/extdata/jennylind.yaml
/usr/lib64/R/library/data.tree/extdata/portfolio.csv
/usr/lib64/R/library/data.tree/extdata/useR15.csv
/usr/lib64/R/library/data.tree/help/AnIndex
/usr/lib64/R/library/data.tree/help/aliases.rds
/usr/lib64/R/library/data.tree/help/data.tree.rdb
/usr/lib64/R/library/data.tree/help/data.tree.rdx
/usr/lib64/R/library/data.tree/help/paths.rds
/usr/lib64/R/library/data.tree/html/00Index.html
/usr/lib64/R/library/data.tree/html/R.css
/usr/lib64/R/library/data.tree/tests/testthat.R
/usr/lib64/R/library/data.tree/tests/testthat/test-draw.R
/usr/lib64/R/library/data.tree/tests/testthat/test-treeConstruction.R
/usr/lib64/R/library/data.tree/tests/testthat/test-treeConversionApe.R
/usr/lib64/R/library/data.tree/tests/testthat/test-treeConversionDataFrame.R
/usr/lib64/R/library/data.tree/tests/testthat/test-treeConversionDendrogram.R
/usr/lib64/R/library/data.tree/tests/testthat/test-treeConversionList.R
/usr/lib64/R/library/data.tree/tests/testthat/test-treeConversionParty.R
/usr/lib64/R/library/data.tree/tests/testthat/test-treeConversionRpart.R
/usr/lib64/R/library/data.tree/tests/testthat/test-treeConversionigraph.R
/usr/lib64/R/library/data.tree/tests/testthat/test-treeDocu.R
/usr/lib64/R/library/data.tree/tests/testthat/test-treeMethods.R
/usr/lib64/R/library/data.tree/tests/testthat/test-treeMethodsSideEffect.R
/usr/lib64/R/library/data.tree/tests/testthat/test-util.R
